// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJCoWoDnLWtiCQohM5XGTqnI2yqq4cVA',
    appId: '1:651268094173:web:bedd02fb520f8559b24334',
    messagingSenderId: '651268094173',
    projectId: 'benjamin-8eb28',
    authDomain: 'benjamin-8eb28.firebaseapp.com',
    storageBucket: 'benjamin-8eb28.appspot.com',
    measurementId: 'G-TKNX74XPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyAlsOMKN-YLp8BkuSbePznEw02aPV8B8',
    appId: '1:651268094173:android:4d6e0d730501b476b24334',
    messagingSenderId: '651268094173',
    projectId: 'benjamin-8eb28',
    storageBucket: 'benjamin-8eb28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4Y6f8lNtpmzx-6pbjAYUq5C3OZipObs',
    appId: '1:651268094173:ios:244353ddee2212d7b24334',
    messagingSenderId: '651268094173',
    projectId: 'benjamin-8eb28',
    storageBucket: 'benjamin-8eb28.appspot.com',
    iosBundleId: 'com.example.benjamin',
  );
}
